name: Auto Assign to Project(s)

on:
  issues:
    types: [labeled]
    label:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  
  assign_one_project:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Assign to Project
    steps:
    - name: Assign issues to project TODO
      if: |
        contains(github.event.issue.labels.*.name, 'Planification') && !contains(github.event.issue.labels.*.name, 'Phase1')
      uses: srggrs/assign-one-project-github-action@1.3.1
      with:
        project: 'https://github.com/Bad-Wolf-developpement/portail-implication-parents/projects/1'
        column_name: 'TODO'
    
    - name: Assign issues to project Phase 1
      if: |
        contains(github.event.issue.labels.*.name, 'Phase1')
      uses: srggrs/assign-one-project-github-action@1.3.1
      with:
        project: 'https://github.com/Bad-Wolf-developpement/portail-implication-parents/projects/1'
        column_name: 'Phase 1'
        
    - name: Assign issues to project Phase 1
      if: |
        contains(github.event.issue.labels.*.name, 'Phase2')
      uses: srggrs/assign-one-project-github-action@1.3.1
      with:
        project: 'https://github.com/Bad-Wolf-developpement/portail-implication-parents/projects/1'
        column_name: 'Phase 2'
